### PR TITLE
Random dig server instead of hardcoded one

### PR DESCRIPTION
**Pull request by pich**
Dig command use random root name server [a-m].root-servers.net instead of hardcoded www.apple.com. Not perfect, but better solution.

### CODE REVIEW

**Comment by alterstep** [comment]
Not a good idea in my humble opinion.

Everybody knows what Apple is, but not root-servers.net and if we do that users will think they have been hacked or this is malware.

I don't understand why asking the DNS server you chose what the IP address of apple.com is, is a problem.

**Comment by pich** [comment]
After reconsideration I have to agree with your arguments.

**Comment by 1-61803** [comment]
It seems that issues regarding the query for apple.com are still being opened. Why not give the option to query for another site?

**Comment by 1-61803** [comment]
It seems that issues regarding the query for apple.com are still being opened. Why not give the option to query for another site?

**Comment by alterstep** [comment]
It is not contacting a website, it is checking that the resolver you chose is working. That resolver that will decrypt and handle all your DNS queries.

**Pull request closed without merging**
